FROM node:18

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Generate Prisma client during build
RUN npx prisma generate

# Expose the app port
EXPOSE 3000

# Command to run migrations and seed, then start the development server
CMD ["sh", "-c", "npx prisma migrate deploy && node prisma/seed.js && npm run dev"]
